apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: votingapp-example
    name: postgres-deployment

spec:
  template:
    metadata:
      name: postgres
      labels:
        app: votingapp-example
        name: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: password
  selector:
    matchLabels:
      app: votingapp-example
      name: postgres