apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: votingapp-example
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: votingapp-example
    name: postgres