apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: votingapp-example
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: votingapp-example
    name: redis