apiVersion: v1
kind: Service
metadata:
  name: resultapp-loadbalancer
  labels:
    app: votingapp-example
    name: resultapp-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 80
  selector:
    app: votingapp-example
    name: result
