apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: votingapp-example
    name: worker-deployment
spec:
  template:
    metadata:
      name: worker
      labels:
        app: votingapp-example
        name: worker
    spec:
      containers:
        - name: worker
          image: dockersamples/examplevotingapp_worker
  selector:
    matchLabels:
      name: worker
  replicas: 1